### ISSUE TITLE
class() function updated for matrices in R 4.0

### ISSUE THREAD

**Issue by mohan-rr** [lzhangdc/Robust-Allele-based-Regression-Framework#2]
[R 4.0 update](https://cran.r-project.org/doc/manuals/r-release/NEWS.html) :

_"matrix objects now also inherit from class "array", so e.g., class(diag(1)) is c("matrix", "array"). This invalidates code incorrectly assuming that class(matrix_obj)) has length one."_ 

line 56-58 : 
```
	if(class(y) == 'numeric'){
		y <- matrix(y, ncol=1)
	}
```
after 4.0 a matrix y passed into this function will have an error since class(y) will be length 2. The example data no longer works because of this error

**Comment by lzhangdc** [comment]
Hi,

The problem has now been resolved. Please create another issue if the error message still shows up. 

Thank you!

Best wishes,
Lin
